spring:
  jpa:
    show-sql: true
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: ppc123456
    url: jdbc:mysql://localhost:3306/ppc?characterEncoding=utf-8&useSSL=false&serverTimezone=GMT%2B8
  redis:
     database: 0
     host: 192.168.42.58
     port: 6379
     password:
     jedis:
       pool:
         max-active: 8
         max-wait: -1
         min-idle: 0
         max-idle: 8
     timeout: 50000








